dining_data = {
    "Florida Avenue Dining Hall (FAR)": {
      "FAR Daily Menu": {
        "Sunday, September 26, 2021": {
          "Dinner": {
            "Item Name": {},
            "Fruit Tray": {},
            "Halal Fried Chicken Wings": {},
            "Baked Ziti w/ Italian Sausage & Mushroom": {},
            "Cheese and Fruit Tray with Crackers": {},
            "Mozzarella Cheese Sticks": {},
            "Manhattan Clam Chowder": {},
            "Caesar Salad": {},
            "Sliced Garlic Bread": {},
            "Roasted Broccoli & Shallots": {},
            "Spinach Fettucine": {},
            "Farfalle Pasta": {},
            "Whole Wheat Penne Pasta": {},
            "Pesto Sauce": {},
            "Sharp Cheddar Cheese Sauce": {},
            "Marinara Sauce": {},
            "Italian Meat Sauce": {},
            "Double Chocolate Layer Cake": {}
          },
          "Late Night": {
            "Item Name": {},
            "Bi Bim Bap Bar": {},
            "Bread Sticks": {},
            "Baked Tofu": {},
            "Beef Bulgogi": {},
            "Egg Patty": {},
            "Meatballs": {},
            "Chicken": {},
            "Spring Mix Leafy Greens": {},
            "Fresh Spinach": {},
            "Sliced Mushrooms": {},
            "Red Onion": {},
            "Broccoli Floret Fresh": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Sticky Rice": {},
            "Spaghetti": {},
            "Elbow Macaroni": {},
            "Gochujang Sauce": {},
            "Meat Sauce": {},
            "Marinara Sauce": {},
            "Sharp Cheddar Cheese Sauce": {},
            "Oi Muchim Spicy Cucumber Salad": {},
            "Daikon Slaw": {},
            "Bi Bim Bap Poached Bean Sprouts": {},
            "Bi Bim Bap Pickled Cucumber": {},
            "Bi Bim Bap Sauteed Mushrooms": {},
            "Bacon Bits": {}
          },
          "Order Ahead Pizza (4:30-8pm)": {
            "Item Name": {},
            "Three Cheese Pizza": {},
            "Pizza Sauce": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Olive Oil": {},
            "Pepperoni": {},
            "Pineapple Tidbits": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Sliced Mushrooms": {},
            "Italian Sausage": {},
            "Sliced Peppers": {},
            "Chicken": {},
            "Fresh Spinach": {},
            "Diced Ham": {},
            "Red Onion": {},
            "Fresh Diced Tomatoes": {},
            "Hard Salami": {},
            "Jalape\u00f1o Peppers": {},
            "Black Olives": {},
            "Olives Green Sliced": {},
            "Bacon Bits": {},
            "Minced Garlic": {}
          }
        }
      },
      "Build Your Own": {
        "Friday, September 24, 2021": {
          "Salad Bar": {
            "Item Name": {},
            "Granny Smith Apples": {},
            "Banana": {},
            "Kiwi": {},
            "Anjou Pears": {},
            "Navel Orange": {},
            "Sliced Pears": {},
            "Hard Cooked Eggs": {},
            "Firm Tofu": {},
            "Tuna Fish": {},
            "Artichoke Hearts": {},
            "Lettuce": {},
            "Shredded Carrots": {},
            "Cherry Tomatoes": {},
            "Black Olives": {},
            "Sliced Water Chestnuts": {},
            "Garbanzo Beans": {},
            "Fresh Spinach": {},
            "Carrot Sticks": {},
            "Celery Sticks": {},
            "Red Onion": {},
            "Trimmed Radishes": {},
            "Jalape\u00f1o Peppers": {},
            "Sliced Mushrooms": {},
            "Broccoli Florets": {},
            "Trimmed Cauliflower": {},
            "Peppers": {},
            "Corn": {},
            "Cucumbers": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Feta Cheese": {},
            "Shredded Cheddar Cheese": {},
            "Cottage Cheese": {},
            "Prairie Farms Blueberry Yogurt": {},
            "Prairie Farms Cherry Vanilla Yogurt": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Creamy Caesar Dressing": {},
            "Golden Italian Dressing": {},
            "Honey Mustard Dressing": {},
            "French Dressing": {},
            "Ranch Dressing": {},
            "Seeds Sunflower Kernel": {},
            "Bacon Bits": {},
            "Chex Mix": {},
            "Seedless Raisins": {},
            "Saltine Crackers": {},
            "Prairie Farms Vanilla Yogurt": {},
            "Jell-O": {}
          },
          "Ice Cream": {
            "Item Name": {},
            "Hershey's Chocolate Syrup": {},
            "Rainbow Sprinkles": {},
            "Oreo Cookies Ice Cream Topping": {},
            "Heath Chocolate Almond Toffee Topping": {},
            "Reeses Pieces Ice Cream Topping": {},
            "Ice Cream Vanilla Soft Serve": {},
            "Ice Cream Chocolate Soft Serve": {},
            "Sugar Ice Cream Cone": {},
            "Bellshape Ice Cream Cone": {}
          },
          "Beverages": {
            "Item Name": {},
            "Milk Chocolate 1%  5 gal Disp": {},
            "Sprite Zero": {},
            "Sprite": {},
            "Pibb Xtra": {},
            "Mello Yello Soda": {},
            "Fanta Orange Soda": {},
            "Diet Coke": {},
            "Coke Classic": {},
            "Cherry Coke": {},
            "Barq's Root Beer": {},
            "Mountain Blast POWERade": {},
            "Minute Maid Lemonade": {},
            "Passion Fruit and Guava Juice": {},
            "Grape Juice": {},
            "Citrus Peach Juice": {},
            "Apple Juice": {},
            "Cranberry Juice": {},
            "Skim Milk": {},
            "Strawberry Kiwi Juice": {},
            "2% Milk": {},
            "Coffee Brewed Plain": {},
            "Sugar Packets": {},
            "Medium Hot Tea": {},
            "Hot Chocolate": {},
            "Ftn Syrup Tea Green": {},
            "Sweet Black Tea": {},
            "Unsweet Black Tea": {}
          },
          "Waffle Bar": {
            "Item Name": {},
            "Waffles": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Organic Granola": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Pancake Syrup": {},
            "Honey": {},
            "Powdered Sugar": {},
            "Hershey's Chocolate Syrup": {},
            "Cinnamon Sugar": {},
            "Sliced Strawberries": {},
            "Chocolate Pudding": {},
            "Vanilla Pudding": {}
          },
          "Cereal": {
            "Item Name": {},
            "Capt'n Crunch": {},
            "Cheerios": {},
            "Cinnamon Toast Crunch Cereal": {},
            "Froot Loops": {},
            "Cocoa Puffs": {},
            "Frosted Flakes": {},
            "Kashi Go Lean Crunch": {},
            "Frosted Mini Wheat": {},
            "Lucky Charms Cereal": {},
            "Golden Grahams": {},
            "Reese's Puffs": {},
            "Rice Krispies": {},
            "Raisin Bran": {},
            "Rice Chex": {}
          },
          "Deli & Bagel Bar": {
            "Item Name": {},
            "Pork & Beef Bologna": {},
            "Hummus": {},
            "Roasted Red Pepper Hummus": {},
            "Egg Salad": {},
            "Tuna Salad": {},
            "Alpha Bakery Multigrain Bread": {},
            "White Sandwich Bread": {},
            "Lite Wheat Sandwich Bread": {},
            "Wheat Sandwich Bread": {},
            "Plain Bagel": {},
            "100% Wheat Bagel": {},
            "Blueberry Bagel": {},
            "Cinnamon Raisin Bagel": {},
            "Deli Roast Beef": {},
            "Smoked Deli Ham": {},
            "Turkey Breast": {},
            "Green Leaf Lettuce": {},
            "Dill Pickle Slices": {},
            "Tomatoes": {},
            "Red Onion": {},
            "Provolone Cheese": {},
            "Sliced Pepper Jack Cheese": {},
            "American Cheese Slice": {},
            "Cheddar Cheese": {},
            "Swiss Cheese": {},
            "Cream Cheese": {},
            "Cinnamon Spread": {},
            "Mustard": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Ketchup": {},
            "Sweet Pickle Relish": {},
            "Mayonnaise": {},
            "Whipped Salad Dressing": {}
          },
          "Condiments": {
            "Item Name": {},
            "Philadelphia Cream Cheese Cup": {},
            "Strawberry Cream Cheese": {},
            "Ketchup": {},
            "Honey": {},
            "Cheese Cream Philly Garden Vegetable Cup": {},
            "Cheese Cream Philly Cup Light": {}
          }
        }
      }
    },
    "Ikenberry Dining Center (IKE)": {
      "Baked Expectations": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Iced Chocolate Cake Donuts": {},
            "Lemon Poppy Muffin": {},
            "Pistachio Muffin": {},
            "Blueberry Danish": {}
          },
          "Lunch": {
            "Item Name": {},
            "Rice Krispies Treats": {},
            "Chocolate Chip Cookies": {},
            "White Chocolate Macadamia Nut Cookie": {},
            "Oatmeal Raisin Cookies": {},
            "Raspberry Cream Cheese Walnut Bars": {}
          },
          "Dinner": {
            "Item Name": {},
            "Italian Lemon Layer Cake": {},
            "Strawberry Shortcake Layer Cake": {},
            "Chocolate Cake (contains almonds)": {}
          }
        }
      },
      "Don's Chophouse": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Halal White BBQ Grilled Chicken Breast": {},
            "Breaded Catfish Filet": {},
            "Crinkle Cut Fries": {},
            "Hamburger Bun": {},
            "Sauteed Vegetable Medley": {},
            "Cheese Sauce": {},
            "Sweet Baby Ray's BBQ Sauce": {}
          }
        }
      },
      "Euclid Street Deli": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Fruit Tray": {},
            "Grapefruit Halves": {},
            "Banana": {},
            "Navel Orange": {},
            "Mullen's Applesauce": {},
            "Hard Cooked Eggs": {},
            "Oatmeal": {}
          },
          "Lunch": {
            "Item Name": {},
            "Mullen's Applesauce": {},
            "Moroccan Lentil Soup": {},
            "New England Clam Chowder": {},
            "Tuna Salad": {},
            "Seafood Salad": {}
          },
          "Dinner": {
            "Item Name": {},
            "Mullen's Applesauce": {},
            "Moroccan Lentil Soup": {},
            "New England Clam Chowder": {},
            "Tuna Salad": {},
            "Seafood Salad": {}
          }
        }
      },
      "Gregory Drive Diner": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Fruit Tray": {},
            "Whole Fresh Fruit": {},
            "Grapefruit Halves": {},
            "Scrambled Eggs": {},
            "Hard Cooked Eggs": {},
            "Pork Sausage Patties": {},
            "Vegetarian Sausage Patty": {},
            "Tofu Scramble": {},
            "Fried French Toast Sticks": {},
            "Oatmeal": {},
            "Tater-Tots": {},
            "Pancake Syrup": {},
            "Scrambled Egg Toppings": {}
          },
          "Lunch": {
            "Item Name": {},
            "Boneless Buffalo Chicken Wings": {},
            "Spicy Black Bean Burger Patty": {},
            "Crinkle Cut Fries": {},
            "Carrot & Celery Sticks Platter": {},
            "Gourmet Hamburger Bun": {},
            "Garlic & Herb Roasted Cauliflower": {},
            "Ranch Dressing": {},
            "Bleu Cheese Dressing": {}
          },
          "Dinner": {
            "Item Name": {},
            "Tilapia with Julienne Vegetables": {},
            "Pesto Turkey Filet": {},
            "Assorted Dinner Rolls": {},
            "Chef's Choice Vegetable": {},
            "Roasted Potato Melange": {}
          }
        }
      },
      "Hortensia's": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Poke Bowl": {},
            "Smoked Tofu Steak": {},
            "Daikon Slaw": {},
            "Marinated Poke Tuna": {},
            "Spring Mix Leafy Greens": {},
            "Sticky Rice": {},
            "Sriracha Mayonnaise": {},
            "Hoisin Sauce": {},
            "Light Soy Sauce": {},
            "Sriracha Sauce": {},
            "Edamame": {},
            "Nori": {},
            "Shredded Carrots": {},
            "Fresh Diced Cucumber": {},
            "Jalape\u00f1o Peppers": {},
            "Fresh Bean Sprouts": {},
            "Sliced Scallions": {}
          }
        }
      },
      "Penne Lane": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Meatballs": {},
            "Sliced Garlic Bread": {},
            "Veef Crumbles": {},
            "Farfalle Pasta": {},
            "Marinara Sauce": {},
            "Alfredo Sauce": {}
          },
          "Dinner": {
            "Item Name": {},
            "Meatballs": {},
            "Seafood Salad": {},
            "Bread Sticks": {},
            "Veef Crumbles": {},
            "Farfalle Pasta": {},
            "Marinara Sauce": {},
            "Creamy Pesto Sauce": {}
          }
        }
      },
      "Prairie Fire": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "BBQ Chicken Pizza": {},
            "Pepperoni Pizza": {},
            "Thin Crust Three Cheese Pizza": {},
            "Cheese Sticks": {}
          }
        }
      },
      "Soytainly": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Chipotle Chili Cheeze Fries": {},
            "Garlic & Herb Roasted Cauliflower": {},
            "Quinoa": {},
            "Illinois-Grown Brown Rice": {}
          },
          "Dinner": {
            "Item Name": {},
            "Vegetable Stir Fry with Edamame": {},
            "Chef's Choice Vegetable": {},
            "Illinois-Grown Brown Rice": {},
            "Quinoa": {}
          }
        }
      },
      "Build Your Own": {
        "Friday, September 24, 2021": {
          "Salad Bar": {
            "Item Name": {},
            "Granny Smith Apples": {},
            "Banana": {},
            "Kiwi": {},
            "Anjou Pears": {},
            "Navel Orange": {},
            "Sliced Pears": {},
            "Hard Cooked Eggs": {},
            "Firm Tofu": {},
            "Tuna Fish": {},
            "Artichoke Hearts": {},
            "Lettuce": {},
            "Shredded Carrots": {},
            "Cherry Tomatoes": {},
            "Black Olives": {},
            "Sliced Water Chestnuts": {},
            "Garbanzo Beans": {},
            "Fresh Spinach": {},
            "Carrot Sticks": {},
            "Celery Sticks": {},
            "Red Onion": {},
            "Trimmed Radishes": {},
            "Jalape\u00f1o Peppers": {},
            "Sliced Mushrooms": {},
            "Broccoli Florets": {},
            "Trimmed Cauliflower": {},
            "Peppers": {},
            "Corn": {},
            "Cucumbers": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Feta Cheese": {},
            "Shredded Cheddar Cheese": {},
            "Cottage Cheese": {},
            "Prairie Farms Blueberry Yogurt": {},
            "Prairie Farms Cherry Vanilla Yogurt": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Creamy Caesar Dressing": {},
            "Golden Italian Dressing": {},
            "Honey Mustard Dressing": {},
            "French Dressing": {},
            "Ranch Dressing": {},
            "Seeds Sunflower Kernel": {},
            "Bacon Bits": {},
            "Chex Mix": {},
            "Seedless Raisins": {},
            "Saltine Crackers": {},
            "Prairie Farms Vanilla Yogurt": {},
            "Jell-O": {}
          },
          "Ice Cream": {
            "Item Name": {},
            "Hershey's Chocolate Syrup": {},
            "Rainbow Sprinkles": {},
            "Oreo Cookies Ice Cream Topping": {},
            "Heath Chocolate Almond Toffee Topping": {},
            "Reeses Pieces Ice Cream Topping": {},
            "Ice Cream Vanilla Soft Serve": {},
            "Ice Cream Chocolate Soft Serve": {},
            "Sugar Ice Cream Cone": {},
            "Bellshape Ice Cream Cone": {}
          },
          "Beverages": {
            "Item Name": {},
            "Milk Chocolate 1%  5 gal Disp": {},
            "Sprite Zero": {},
            "Sprite": {},
            "Pibb Xtra": {},
            "Mello Yello Soda": {},
            "Fanta Orange Soda": {},
            "Diet Coke": {},
            "Coke Classic": {},
            "Cherry Coke": {},
            "Barq's Root Beer": {},
            "Mountain Blast POWERade": {},
            "Minute Maid Lemonade": {},
            "Passion Fruit and Guava Juice": {},
            "Grape Juice": {},
            "Citrus Peach Juice": {},
            "Apple Juice": {},
            "Cranberry Juice": {},
            "Skim Milk": {},
            "Strawberry Kiwi Juice": {},
            "2% Milk": {},
            "Coffee Brewed Plain": {},
            "Sugar Packets": {},
            "Medium Hot Tea": {},
            "Hot Chocolate": {},
            "Ftn Syrup Tea Green": {},
            "Sweet Black Tea": {},
            "Unsweet Black Tea": {}
          },
          "Waffle Bar": {
            "Item Name": {},
            "Waffles": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Organic Granola": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Pancake Syrup": {},
            "Honey": {},
            "Powdered Sugar": {},
            "Hershey's Chocolate Syrup": {},
            "Cinnamon Sugar": {},
            "Sliced Strawberries": {},
            "Chocolate Pudding": {},
            "Vanilla Pudding": {}
          },
          "Cereal": {
            "Item Name": {},
            "Capt'n Crunch": {},
            "Cheerios": {},
            "Cinnamon Toast Crunch Cereal": {},
            "Froot Loops": {},
            "Cocoa Puffs": {},
            "Frosted Flakes": {},
            "Kashi Go Lean Crunch": {},
            "Frosted Mini Wheat": {},
            "Lucky Charms Cereal": {},
            "Golden Grahams": {},
            "Reese's Puffs": {},
            "Rice Krispies": {},
            "Raisin Bran": {},
            "Rice Chex": {}
          },
          "Deli & Bagel Bar": {
            "Item Name": {},
            "Pork & Beef Bologna": {},
            "Hummus": {},
            "Roasted Red Pepper Hummus": {},
            "Egg Salad": {},
            "Tuna Salad": {},
            "Alpha Bakery Multigrain Bread": {},
            "White Sandwich Bread": {},
            "Lite Wheat Sandwich Bread": {},
            "Wheat Sandwich Bread": {},
            "Plain Bagel": {},
            "100% Wheat Bagel": {},
            "Blueberry Bagel": {},
            "Cinnamon Raisin Bagel": {},
            "Deli Roast Beef": {},
            "Smoked Deli Ham": {},
            "Turkey Breast": {},
            "Green Leaf Lettuce": {},
            "Dill Pickle Slices": {},
            "Tomatoes": {},
            "Red Onion": {},
            "Provolone Cheese": {},
            "Sliced Pepper Jack Cheese": {},
            "American Cheese Slice": {},
            "Cheddar Cheese": {},
            "Swiss Cheese": {},
            "Cream Cheese": {},
            "Cinnamon Spread": {},
            "Mustard": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Ketchup": {},
            "Sweet Pickle Relish": {},
            "Mayonnaise": {},
            "Whipped Salad Dressing": {}
          },
          "Condiments": {
            "Item Name": {},
            "Philadelphia Cream Cheese Cup": {},
            "Strawberry Cream Cheese": {},
            "Ketchup": {},
            "Honey": {},
            "Cheese Cream Philly Garden Vegetable Cup": {},
            "Cheese Cream Philly Cup Light": {}
          }
        }
      }
    },
    "Illinois Street Dining Center (ISR)": {
      "Fusion 48": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Aloo Gobi with Mixed Vegetables": {},
            "Chicken Thigh Tandoori Masala Halal": {},
            "Toasted Chickpeas": {},
            "Garlic & Butter Naan": {},
            "Fresh Mint": {},
            "Spring Mix Leafy Greens": {},
            "Fresh Diced Cucumber": {},
            "Fresh Diced Tomatoes": {},
            "Basmati Rice": {},
            "Mango, Almond & Raisin Chutney": {},
            "Tikka Masala Sauce": {},
            "Plain Greek Yogurt": {},
            "Fresh Cilantro": {},
            "Onions French Fried": {},
            "Limes": {}
          },
          "Dinner": {
            "Item Name": {},
            "Beef Kofta": {},
            "Aloo Choley with Potatoes": {},
            "Mirch Pakora": {},
            "Basmati Rice": {}
          }
        }
      },
      "Inclusive Solutions": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Halal Herb Grilled Chicken Breast": {},
            "Good Karma Bowl": {},
            "Red Onion": {},
            "Avocado Halves": {},
            "Lemon Blueberry Muffins": {}
          },
          "Dinner": {
            "Item Name": {},
            "Halal Herb Grilled Chicken Breast": {},
            "Good Karma Bowl": {},
            "Red Onion": {},
            "Avocado Halves": {},
            "Lemon Blueberry Muffins": {}
          }
        }
      },
      "Table 1867": {},
      "Grains & Greens": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Longevity Fruit & Nut Trail Mix": {},
            "Roasted Red Pepper & Gouda Soup": {},
            "New England Clam Chowder": {},
            "Hummus": {},
            "BLT Pasta Salad": {},
            "Pita Bread": {},
            "Smoked Salmon": {},
            "Millet": {}
          },
          "Dinner": {
            "Item Name": {},
            "Longevity Fruit & Nut Trail Mix": {},
            "Roasted Red Pepper & Gouda Soup": {},
            "New England Clam Chowder": {},
            "Hummus": {},
            "BLT Pasta Salad": {},
            "Pita Bread": {},
            "Smoked Salmon": {},
            "Millet": {}
          }
        }
      },
      "Grillworks": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Whole Fresh Fruit": {},
            "Fruit Tray": {},
            "Hard Cooked Eggs": {},
            "Tofu Scramble": {},
            "Bacon": {},
            "Blueberry Pancakes": {},
            "Scrambled Eggs": {},
            "Oatmeal": {},
            "Herb Roasted Zucchini & Tomato Bake": {},
            "White Rice": {},
            "Tri-tater Potatoes": {},
            "Pancake Syrup": {}
          },
          "Lunch": {
            "Item Name": {},
            "Breaded Catfish Filet": {},
            "Caprese Sandwich": {},
            "Beef Chili": {},
            "Creamy Cole Slaw": {},
            "French Sandwich Roll": {},
            "Cornbread": {},
            "Steamed Spinach": {},
            "Northern Beans": {},
            "Sweet Potato Fries": {},
            "Spelt": {},
            "Beer BBQ Sauce": {},
            "Cajun A\u00efoli": {},
            "Chow Chow": {}
          },
          "Dinner": {
            "Item Name": {},
            "Award-Winning Zucchini Quinoa Lasagna": {},
            "Mussels w/Tomatoes & Tarragon": {},
            "Beef Chili": {},
            "Creamy Cole Slaw": {},
            "Cornbread": {},
            "Northern Beans": {},
            "Fresh Steamed Spinach": {},
            "Spelt": {},
            "Linguine Pasta": {},
            "Beer BBQ Sauce": {}
          }
        }
      },
      "Latitude": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Good Karma Bowl": {},
            "Smoked Hummus": {},
            "Halal Herb Grilled Chicken Breast": {},
            "Hard Cooked Eggs": {},
            "Roasted Beets": {},
            "Roasted Carrots tossed with Fresh Herbs": {},
            "Spring Mix Leafy Greens": {},
            "Fried Kale": {},
            "Red Onion": {},
            "Roasted Red Peppers": {},
            "Feta Cheese": {},
            "Shredded Parmesan Cheese": {},
            "Quinoa": {},
            "Spelt": {},
            "Mashed Sweet Potatoes": {},
            "Dressing Miso": {},
            "Sesame Ginger Dressing": {},
            "Avocado Pulp Fresh": {}
          }
        }
      },
      "Saporito Pasta": {
        "Friday, September 24, 2021": {
          "Dinner": {
            "Item Name": {},
            "Bread Sticks": {},
            "Firm Tofu": {},
            "Diced Chicken Breast": {},
            "Diced Ham": {},
            "Bacon Bits": {},
            "Ginger Root": {},
            "Fresh Steamed Broccoli": {},
            "Fresh Spinach": {},
            "Sliced Mushrooms": {},
            "Fresh Diced Tomatoes": {},
            "Diced Green Peppers": {},
            "Red Onion": {},
            "Fresh Pasta": {},
            "Sustainable Student Farm Marinara Sauce": {},
            "Pesto Sauce": {},
            "Smoked Gouda Cheese Sauce": {}
          }
        }
      },
      "Saporito Pizza": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Sausage Pizza": {},
            "Thin Crust Three Cheese Pizza": {},
            "Valentino Pizza": {},
            "Fried Butterfly Shrimp": {},
            "Greek Salad": {}
          },
          "Dinner": {
            "Item Name": {},
            "Sausage Pizza": {},
            "Thin Crust Three Cheese Pizza": {},
            "Valentino Pizza": {},
            "Greek Salad": {}
          }
        }
      },
      "Rise & Dine": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Whole Fresh Fruit": {},
            "Fruit Tray": {},
            "Bagel Bar": {},
            "Waffle Bar": {},
            "Yogurt Bar": {}
          }
        }
      },
      "Cafe a la Crumb": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Pistachio Muffin": {},
            "Lemon Poppy Muffin": {},
            "Assorted Danishes": {},
            "Assorted Donuts": {}
          },
          "Lunch": {},
          "Dinner": {}
        }
      },
      "Build Your Own": {
        "Friday, September 24, 2021": {
          "Salad Bar": {
            "Item Name": {},
            "Granny Smith Apples": {},
            "Banana": {},
            "Kiwi": {},
            "Anjou Pears": {},
            "Navel Orange": {},
            "Sliced Pears": {},
            "Hard Cooked Eggs": {},
            "Firm Tofu": {},
            "Tuna Fish": {},
            "Artichoke Hearts": {},
            "Lettuce": {},
            "Shredded Carrots": {},
            "Cherry Tomatoes": {},
            "Black Olives": {},
            "Sliced Water Chestnuts": {},
            "Garbanzo Beans": {},
            "Fresh Spinach": {},
            "Carrot Sticks": {},
            "Celery Sticks": {},
            "Red Onion": {},
            "Trimmed Radishes": {},
            "Jalape\u00f1o Peppers": {},
            "Sliced Mushrooms": {},
            "Broccoli Florets": {},
            "Trimmed Cauliflower": {},
            "Peppers": {},
            "Corn": {},
            "Cucumbers": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Feta Cheese": {},
            "Shredded Cheddar Cheese": {},
            "Cottage Cheese": {},
            "Prairie Farms Blueberry Yogurt": {},
            "Prairie Farms Cherry Vanilla Yogurt": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Creamy Caesar Dressing": {},
            "Golden Italian Dressing": {},
            "Honey Mustard Dressing": {},
            "French Dressing": {},
            "Ranch Dressing": {},
            "Seeds Sunflower Kernel": {},
            "Bacon Bits": {},
            "Chex Mix": {},
            "Seedless Raisins": {},
            "Saltine Crackers": {},
            "Prairie Farms Vanilla Yogurt": {},
            "Jell-O": {}
          },
          "Ice Cream": {
            "Item Name": {},
            "Hershey's Chocolate Syrup": {},
            "Rainbow Sprinkles": {},
            "Oreo Cookies Ice Cream Topping": {},
            "Heath Chocolate Almond Toffee Topping": {},
            "Reeses Pieces Ice Cream Topping": {},
            "Ice Cream Vanilla Soft Serve": {},
            "Ice Cream Chocolate Soft Serve": {},
            "Sugar Ice Cream Cone": {},
            "Bellshape Ice Cream Cone": {}
          },
          "Beverages": {
            "Item Name": {},
            "Milk Chocolate 1%  5 gal Disp": {},
            "Sprite Zero": {},
            "Sprite": {},
            "Pibb Xtra": {},
            "Mello Yello Soda": {},
            "Fanta Orange Soda": {},
            "Diet Coke": {},
            "Coke Classic": {},
            "Cherry Coke": {},
            "Barq's Root Beer": {},
            "Mountain Blast POWERade": {},
            "Minute Maid Lemonade": {},
            "Passion Fruit and Guava Juice": {},
            "Grape Juice": {},
            "Citrus Peach Juice": {},
            "Apple Juice": {},
            "Cranberry Juice": {},
            "Skim Milk": {},
            "Strawberry Kiwi Juice": {},
            "2% Milk": {},
            "Coffee Brewed Plain": {},
            "Sugar Packets": {},
            "Medium Hot Tea": {},
            "Hot Chocolate": {},
            "Ftn Syrup Tea Green": {},
            "Sweet Black Tea": {},
            "Unsweet Black Tea": {}
          },
          "Waffle Bar": {
            "Item Name": {},
            "Waffles": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Organic Granola": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Pancake Syrup": {},
            "Honey": {},
            "Powdered Sugar": {},
            "Hershey's Chocolate Syrup": {},
            "Cinnamon Sugar": {},
            "Sliced Strawberries": {},
            "Chocolate Pudding": {},
            "Vanilla Pudding": {}
          },
          "Cereal": {
            "Item Name": {},
            "Capt'n Crunch": {},
            "Cheerios": {},
            "Cinnamon Toast Crunch Cereal": {},
            "Froot Loops": {},
            "Cocoa Puffs": {},
            "Frosted Flakes": {},
            "Kashi Go Lean Crunch": {},
            "Frosted Mini Wheat": {},
            "Lucky Charms Cereal": {},
            "Golden Grahams": {},
            "Reese's Puffs": {},
            "Rice Krispies": {},
            "Raisin Bran": {},
            "Rice Chex": {}
          },
          "Deli & Bagel Bar": {
            "Item Name": {},
            "Pork & Beef Bologna": {},
            "Hummus": {},
            "Roasted Red Pepper Hummus": {},
            "Egg Salad": {},
            "Tuna Salad": {},
            "Alpha Bakery Multigrain Bread": {},
            "White Sandwich Bread": {},
            "Lite Wheat Sandwich Bread": {},
            "Wheat Sandwich Bread": {},
            "Plain Bagel": {},
            "100% Wheat Bagel": {},
            "Blueberry Bagel": {},
            "Cinnamon Raisin Bagel": {},
            "Deli Roast Beef": {},
            "Smoked Deli Ham": {},
            "Turkey Breast": {},
            "Green Leaf Lettuce": {},
            "Dill Pickle Slices": {},
            "Tomatoes": {},
            "Red Onion": {},
            "Provolone Cheese": {},
            "Sliced Pepper Jack Cheese": {},
            "American Cheese Slice": {},
            "Cheddar Cheese": {},
            "Swiss Cheese": {},
            "Cream Cheese": {},
            "Cinnamon Spread": {},
            "Mustard": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Ketchup": {},
            "Sweet Pickle Relish": {},
            "Mayonnaise": {},
            "Whipped Salad Dressing": {}
          },
          "Condiments": {
            "Item Name": {},
            "Philadelphia Cream Cheese Cup": {},
            "Strawberry Cream Cheese": {},
            "Ketchup": {},
            "Honey": {},
            "Cheese Cream Philly Garden Vegetable Cup": {},
            "Cheese Cream Philly Cup Light": {}
          }
        }
      }
    },
    "Pennsylvania Avenue Dining Hall (PAR)": {
      "Abbondante Pizza & Pasta": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Pepperoni Pizza": {},
            "Three Cheese Pizza": {},
            "California Vegetable Pizza": {},
            "Cheese Sticks": {},
            "Grated Parmesan Cheese": {},
            "Crushed Red Pepper": {}
          },
          "Dinner": {
            "Item Name": {},
            "Pepperoni Pizza": {},
            "Three Cheese Pizza": {},
            "California Vegetable Pizza": {},
            "Cheese Sticks": {},
            "Diced Chicken Breast": {},
            "Meatballs": {},
            "Rotini Pasta": {},
            "Alfredo Sauce": {},
            "Marinara Sauce": {},
            "Grated Parmesan Cheese": {},
            "Crushed Red Pepper": {}
          }
        }
      },
      "Arugula's Salad Bar": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Chicken Salad": {},
            "Firm Tofu": {},
            "Shredded Parmesan Cheese": {},
            "Ranch Dressing": {},
            "Bleu Cheese Dressing": {},
            "French Dressing": {},
            "Golden Italian Dressing": {},
            "Raspberry Vinaigrette Dressing": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {}
          },
          "Dinner": {
            "Item Name": {},
            "Chicken Salad": {},
            "Firm Tofu": {},
            "Shredded Parmesan Cheese": {},
            "Ranch Dressing": {},
            "Bleu Cheese Dressing": {},
            "French Dressing": {},
            "Golden Italian Dressing": {},
            "Raspberry Vinaigrette Dressing": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {}
          }
        }
      },
      "La Avenida": {
        "Friday, September 24, 2021": {
          "Breakfast": {
            "Item Name": {},
            "Hard Cooked Eggs": {},
            "Scrambled Eggs": {},
            "Pork Sausage Patties": {},
            "Vegetarian Sausage Patty": {},
            "Baked French Toast Sticks": {},
            "Tofu Scramble": {},
            "Halal Congee Rice Soup": {},
            "Oatmeal": {},
            "White Rice": {},
            "Tater-Tots": {},
            "Pancake Syrup": {},
            "Scrambled Egg Toppings": {},
            "Halal Congee Toppings (w/ peanuts)": {}
          },
          "Lunch": {
            "Item Name": {},
            "Sliced Philly Beef": {},
            "Sliced Chicken": {},
            "Baked Tofu": {},
            "Steamed Vegetable Pot Stickers": {},
            "Pho": {},
            "Spring Mix Leafy Greens": {},
            "Rice Stick Noodles": {},
            "Limes": {},
            "Fresh Thai Basil": {},
            "Fresh Cilantro": {},
            "Jalape\u00f1o Peppers": {},
            "Fresh Bean Sprouts": {}
          },
          "Dinner": {
            "Item Name": {},
            "Garlic Studded Pork Loin": {},
            "Butter Herb Tilapia": {},
            "Jasmine Rice": {}
          }
        }
      },
      "Provolone Soup, Sandwich & Dessert Station": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "New England Clam Chowder": {},
            "Chocolate Chip Cookie": {}
          },
          "Dinner": {
            "Item Name": {},
            "New England Clam Chowder": {},
            "Lemon Bars": {}
          },
          "Light Lunch": {
            "Item Name": {},
            "New England Clam Chowder": {},
            "Chocolate Chip Cookie": {}
          }
        }
      },
      "Sky Garden": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Chicken": {},
            "Scrambled Eggs": {},
            "Firm Tofu": {},
            "Sliced Beef Strips": {},
            "Bamboo Shoots": {},
            "Sliced Water Chestnuts": {},
            "Fresh Bean Sprouts": {},
            "Onions": {},
            "Edamame": {},
            "Sliced Mushrooms": {},
            "Steamed Broccoli Florets": {},
            "Bok Choy": {},
            "Shredded Carrots": {},
            "Sliced Peppers": {},
            "Snow Peas": {},
            "Baby Corn": {},
            "White Rice": {},
            "Udon Noodles": {},
            "Rice Noodles": {},
            "Purple Rice": {},
            "Szechuan Sauce": {},
            "Teriyaki Sauce": {},
            "Asian Garlic Chili Sauce": {},
            "Ying's Sweet & Sour Sauce": {},
            "Sambal Paste": {},
            "Thai Chili Sauce": {},
            "Ying's Orange Sauce": {},
            "Stir Fry Sauce": {},
            "General Tso's Sauce": {},
            "Kung Pao Sauce": {},
            "Ying's Korean BBQ Sauce": {},
            "Napa Cabbage Kimchi": {}
          },
          "Dinner": {
            "Item Name": {},
            "Shrimp": {},
            "Chicken": {},
            "Scrambled Eggs": {},
            "Firm Tofu": {},
            "Sliced Beef Strips": {},
            "Bamboo Shoots": {},
            "Sliced Water Chestnuts": {},
            "Fresh Bean Sprouts": {},
            "Onions": {},
            "Edamame": {},
            "Sliced Mushrooms": {},
            "Steamed Broccoli Florets": {},
            "Bok Choy": {},
            "Shredded Carrots": {},
            "Sliced Peppers": {},
            "Snow Peas": {},
            "Baby Corn": {},
            "White Rice": {},
            "Udon Noodles": {},
            "Rice Noodles": {},
            "Purple Rice": {},
            "Szechuan Sauce": {},
            "Teriyaki Sauce": {},
            "Asian Garlic Chili Sauce": {},
            "Ying's Sweet & Sour Sauce": {},
            "Sambal Paste": {},
            "Thai Chili Sauce": {},
            "Ying's Orange Sauce": {},
            "Stir Fry Sauce": {},
            "General Tso's Sauce": {},
            "Kung Pao Sauce": {},
            "Ying's Korean BBQ Sauce": {},
            "Napa Cabbage Kimchi": {}
          }
        }
      },
      "Build Your Own": {
        "Friday, September 24, 2021": {
          "Salad Bar": {
            "Item Name": {},
            "Granny Smith Apples": {},
            "Banana": {},
            "Kiwi": {},
            "Anjou Pears": {},
            "Navel Orange": {},
            "Sliced Pears": {},
            "Hard Cooked Eggs": {},
            "Firm Tofu": {},
            "Tuna Fish": {},
            "Artichoke Hearts": {},
            "Lettuce": {},
            "Shredded Carrots": {},
            "Cherry Tomatoes": {},
            "Black Olives": {},
            "Sliced Water Chestnuts": {},
            "Garbanzo Beans": {},
            "Fresh Spinach": {},
            "Carrot Sticks": {},
            "Celery Sticks": {},
            "Red Onion": {},
            "Trimmed Radishes": {},
            "Jalape\u00f1o Peppers": {},
            "Sliced Mushrooms": {},
            "Broccoli Florets": {},
            "Trimmed Cauliflower": {},
            "Peppers": {},
            "Corn": {},
            "Cucumbers": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Feta Cheese": {},
            "Shredded Cheddar Cheese": {},
            "Cottage Cheese": {},
            "Prairie Farms Blueberry Yogurt": {},
            "Prairie Farms Cherry Vanilla Yogurt": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Creamy Caesar Dressing": {},
            "Golden Italian Dressing": {},
            "Honey Mustard Dressing": {},
            "French Dressing": {},
            "Ranch Dressing": {},
            "Seeds Sunflower Kernel": {},
            "Bacon Bits": {},
            "Chex Mix": {},
            "Seedless Raisins": {},
            "Saltine Crackers": {},
            "Prairie Farms Vanilla Yogurt": {},
            "Jell-O": {}
          },
          "Ice Cream": {
            "Item Name": {},
            "Hershey's Chocolate Syrup": {},
            "Rainbow Sprinkles": {},
            "Oreo Cookies Ice Cream Topping": {},
            "Heath Chocolate Almond Toffee Topping": {},
            "Reeses Pieces Ice Cream Topping": {},
            "Ice Cream Vanilla Soft Serve": {},
            "Ice Cream Chocolate Soft Serve": {},
            "Sugar Ice Cream Cone": {},
            "Bellshape Ice Cream Cone": {}
          },
          "Beverages": {
            "Item Name": {},
            "Milk Chocolate 1%  5 gal Disp": {},
            "Sprite Zero": {},
            "Sprite": {},
            "Pibb Xtra": {},
            "Mello Yello Soda": {},
            "Fanta Orange Soda": {},
            "Diet Coke": {},
            "Coke Classic": {},
            "Cherry Coke": {},
            "Barq's Root Beer": {},
            "Mountain Blast POWERade": {},
            "Minute Maid Lemonade": {},
            "Passion Fruit and Guava Juice": {},
            "Grape Juice": {},
            "Citrus Peach Juice": {},
            "Apple Juice": {},
            "Cranberry Juice": {},
            "Skim Milk": {},
            "Strawberry Kiwi Juice": {},
            "2% Milk": {},
            "Coffee Brewed Plain": {},
            "Sugar Packets": {},
            "Medium Hot Tea": {},
            "Hot Chocolate": {},
            "Ftn Syrup Tea Green": {},
            "Sweet Black Tea": {},
            "Unsweet Black Tea": {}
          },
          "Waffle Bar": {
            "Item Name": {},
            "Waffles": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Organic Granola": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Pancake Syrup": {},
            "Honey": {},
            "Powdered Sugar": {},
            "Hershey's Chocolate Syrup": {},
            "Cinnamon Sugar": {},
            "Sliced Strawberries": {},
            "Chocolate Pudding": {},
            "Vanilla Pudding": {}
          },
          "Cereal": {
            "Item Name": {},
            "Capt'n Crunch": {},
            "Cheerios": {},
            "Cinnamon Toast Crunch Cereal": {},
            "Froot Loops": {},
            "Cocoa Puffs": {},
            "Frosted Flakes": {},
            "Kashi Go Lean Crunch": {},
            "Frosted Mini Wheat": {},
            "Lucky Charms Cereal": {},
            "Golden Grahams": {},
            "Reese's Puffs": {},
            "Rice Krispies": {},
            "Raisin Bran": {},
            "Rice Chex": {}
          },
          "Deli & Bagel Bar": {
            "Item Name": {},
            "Pork & Beef Bologna": {},
            "Hummus": {},
            "Roasted Red Pepper Hummus": {},
            "Egg Salad": {},
            "Tuna Salad": {},
            "Alpha Bakery Multigrain Bread": {},
            "White Sandwich Bread": {},
            "Lite Wheat Sandwich Bread": {},
            "Wheat Sandwich Bread": {},
            "Plain Bagel": {},
            "100% Wheat Bagel": {},
            "Blueberry Bagel": {},
            "Cinnamon Raisin Bagel": {},
            "Deli Roast Beef": {},
            "Smoked Deli Ham": {},
            "Turkey Breast": {},
            "Green Leaf Lettuce": {},
            "Dill Pickle Slices": {},
            "Tomatoes": {},
            "Red Onion": {},
            "Provolone Cheese": {},
            "Sliced Pepper Jack Cheese": {},
            "American Cheese Slice": {},
            "Cheddar Cheese": {},
            "Swiss Cheese": {},
            "Cream Cheese": {},
            "Cinnamon Spread": {},
            "Mustard": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Ketchup": {},
            "Sweet Pickle Relish": {},
            "Mayonnaise": {},
            "Whipped Salad Dressing": {}
          },
          "Condiments": {
            "Item Name": {},
            "Philadelphia Cream Cheese Cup": {},
            "Strawberry Cream Cheese": {},
            "Ketchup": {},
            "Honey": {},
            "Cheese Cream Philly Garden Vegetable Cup": {},
            "Cheese Cream Philly Cup Light": {}
          }
        }
      }
    },
    "Lincoln Avenue Dining Hall (LAR)": {
      "LAR Daily Menu": {
        "Friday, September 24, 2021": {
          "Lunch": {
            "Item Name": {},
            "Halal Grilled Ranch Chicken Breast": {},
            "Corona Beer Battered Cod": {},
            "Baked Ziti with Mushrooms": {},
            "Veef Fajitas": {},
            "Roasted Red Pepper & Gouda Soup": {},
            "6\" Flour Tortilla": {},
            "Green Beans": {},
            "Brown Rice Pilaf": {},
            "Natural Cut French Fries": {},
            "Tartar Sauce": {},
            "Lemons": {},
            "Taco Toppings": {},
            "Carnival Cookies": {}
          },
          "Dinner": {
            "Item Name": {},
            "Fish Salmon Side Bourbon Marinated": {},
            "Beef Bulgogi": {},
            "Bi Bim Bap Bar": {},
            "Shells Florentine": {},
            "New England Clam Chowder": {},
            "Sliced Garlic Bread": {},
            "Roasted Sweet Potatoes": {},
            "Chef's Choice Vegetable": {},
            "Bi Bim Bap Rice": {},
            "Bi Bim Bap Poached Bean Sprouts": {},
            "Bi Bim Bap Pickled Cucumber": {},
            "Bi Bim Bap Pickled Daikon": {},
            "Bi Bim Bap Sauteed Mushrooms": {},
            "Bi Bim Bap Poached Spinach": {},
            "Bi Bim Bap Poached Zucchini": {},
            "Texas Torte Cake": {}
          }
        }
      },
      "Build Your Own": {
        "Friday, September 24, 2021": {
          "Salad Bar": {
            "Item Name": {},
            "Granny Smith Apples": {},
            "Banana": {},
            "Kiwi": {},
            "Anjou Pears": {},
            "Navel Orange": {},
            "Sliced Pears": {},
            "Hard Cooked Eggs": {},
            "Firm Tofu": {},
            "Tuna Fish": {},
            "Artichoke Hearts": {},
            "Lettuce": {},
            "Shredded Carrots": {},
            "Cherry Tomatoes": {},
            "Black Olives": {},
            "Sliced Water Chestnuts": {},
            "Garbanzo Beans": {},
            "Fresh Spinach": {},
            "Carrot Sticks": {},
            "Celery Sticks": {},
            "Red Onion": {},
            "Trimmed Radishes": {},
            "Jalape\u00f1o Peppers": {},
            "Sliced Mushrooms": {},
            "Broccoli Florets": {},
            "Trimmed Cauliflower": {},
            "Peppers": {},
            "Corn": {},
            "Cucumbers": {},
            "Shredded Mozzarella/Provelone Blend": {},
            "Feta Cheese": {},
            "Shredded Cheddar Cheese": {},
            "Cottage Cheese": {},
            "Prairie Farms Blueberry Yogurt": {},
            "Prairie Farms Cherry Vanilla Yogurt": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Creamy Caesar Dressing": {},
            "Golden Italian Dressing": {},
            "Honey Mustard Dressing": {},
            "French Dressing": {},
            "Ranch Dressing": {},
            "Seeds Sunflower Kernel": {},
            "Bacon Bits": {},
            "Chex Mix": {},
            "Seedless Raisins": {},
            "Saltine Crackers": {},
            "Prairie Farms Vanilla Yogurt": {},
            "Jell-O": {}
          },
          "Ice Cream": {
            "Item Name": {},
            "Hershey's Chocolate Syrup": {},
            "Rainbow Sprinkles": {},
            "Oreo Cookies Ice Cream Topping": {},
            "Heath Chocolate Almond Toffee Topping": {},
            "Reeses Pieces Ice Cream Topping": {},
            "Ice Cream Vanilla Soft Serve": {},
            "Ice Cream Chocolate Soft Serve": {},
            "Sugar Ice Cream Cone": {},
            "Bellshape Ice Cream Cone": {}
          },
          "Beverages": {
            "Item Name": {},
            "Milk Chocolate 1%  5 gal Disp": {},
            "Sprite Zero": {},
            "Sprite": {},
            "Pibb Xtra": {},
            "Mello Yello Soda": {},
            "Fanta Orange Soda": {},
            "Diet Coke": {},
            "Coke Classic": {},
            "Cherry Coke": {},
            "Barq's Root Beer": {},
            "Mountain Blast POWERade": {},
            "Minute Maid Lemonade": {},
            "Passion Fruit and Guava Juice": {},
            "Grape Juice": {},
            "Citrus Peach Juice": {},
            "Apple Juice": {},
            "Cranberry Juice": {},
            "Skim Milk": {},
            "Strawberry Kiwi Juice": {},
            "2% Milk": {},
            "Coffee Brewed Plain": {},
            "Sugar Packets": {},
            "Medium Hot Tea": {},
            "Hot Chocolate": {},
            "Ftn Syrup Tea Green": {},
            "Sweet Black Tea": {},
            "Unsweet Black Tea": {}
          },
          "Waffle Bar": {
            "Item Name": {},
            "Waffles": {},
            "Prairie Farms Plain Yogurt": {},
            "Prairie Farms Raspberry Yogurt": {},
            "Organic Granola": {},
            "Prairie Farms Strawberry Yogurt": {},
            "Pancake Syrup": {},
            "Honey": {},
            "Powdered Sugar": {},
            "Hershey's Chocolate Syrup": {},
            "Cinnamon Sugar": {},
            "Sliced Strawberries": {},
            "Chocolate Pudding": {},
            "Vanilla Pudding": {}
          },
          "Cereal": {
            "Item Name": {},
            "Capt'n Crunch": {},
            "Cheerios": {},
            "Cinnamon Toast Crunch Cereal": {},
            "Froot Loops": {},
            "Cocoa Puffs": {},
            "Frosted Flakes": {},
            "Kashi Go Lean Crunch": {},
            "Frosted Mini Wheat": {},
            "Lucky Charms Cereal": {},
            "Golden Grahams": {},
            "Reese's Puffs": {},
            "Rice Krispies": {},
            "Raisin Bran": {},
            "Rice Chex": {}
          },
          "Deli & Bagel Bar": {
            "Item Name": {},
            "Pork & Beef Bologna": {},
            "Hummus": {},
            "Roasted Red Pepper Hummus": {},
            "Egg Salad": {},
            "Tuna Salad": {},
            "Alpha Bakery Multigrain Bread": {},
            "White Sandwich Bread": {},
            "Lite Wheat Sandwich Bread": {},
            "Wheat Sandwich Bread": {},
            "Plain Bagel": {},
            "100% Wheat Bagel": {},
            "Blueberry Bagel": {},
            "Cinnamon Raisin Bagel": {},
            "Deli Roast Beef": {},
            "Smoked Deli Ham": {},
            "Turkey Breast": {},
            "Green Leaf Lettuce": {},
            "Dill Pickle Slices": {},
            "Tomatoes": {},
            "Red Onion": {},
            "Provolone Cheese": {},
            "Sliced Pepper Jack Cheese": {},
            "American Cheese Slice": {},
            "Cheddar Cheese": {},
            "Swiss Cheese": {},
            "Cream Cheese": {},
            "Cinnamon Spread": {},
            "Mustard": {},
            "Sweet Baby Ray's BBQ Sauce": {},
            "Ketchup": {},
            "Sweet Pickle Relish": {},
            "Mayonnaise": {},
            "Whipped Salad Dressing": {}
          },
          "Condiments": {
            "Item Name": {},
            "Philadelphia Cream Cheese Cup": {},
            "Strawberry Cream Cheese": {},
            "Ketchup": {},
            "Honey": {},
            "Cheese Cream Philly Garden Vegetable Cup": {},
            "Cheese Cream Philly Cup Light": {}
          }
        }
      }
    },
    "Field of Greens": {},
    "Kosher Kitchen": {},
    "TerraByte": {},
    "InfiniTEA": {},
    "Urbana South Market": {},
    "57 North": {},
    "Caffeinator": {},
    "Good2Go Food Truck": {}
  }